### ISSUE TITLE
UnitCanCut.cs (Code clean)

### ISSUE THREAD

**Issue by 6RimuruTempest9** [fak1ch/FruitNinja#11]
https://github.com/fak1ch/FruitNinja/blob/9dcac90e2290edddda179b93733af0916b251330/Assets/Scripts/GameUnits/UnitCanCut.cs#L25-L29

You can remove string [#25](https://github.com/fak1ch/FruitNinja/blob/9dcac90e2290edddda179b93733af0916b251330/Assets/Scripts/GameUnits/UnitCanCut.cs#L25) and write `var sprites = _utils.GetTwo...` instead string [#29](https://github.com/fak1ch/FruitNinja/blob/9dcac90e2290edddda179b93733af0916b251330/Assets/Scripts/GameUnits/UnitCanCut.cs#L29).

**Comment by fak1ch** [comment]
Wise!
