### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by 6RimuruTempest9** [fak1ch/FruitNinja#17]
https://github.com/fak1ch/FruitNinja/blob/dd639404d1a2bf7f5d84eadc120825f272f72e82/Assets/Scripts/UnitsContainer.cs#L13-L14

Not needed to use "Get" word in property naming.

**Comment by fak1ch** [comment]
Removed all "Get" words from property names!

**Comment by 6RimuruTempest9** [comment]
That's great!
