### ISSUE TITLE
GameInitializer.cs

### ISSUE THREAD

**Issue by 6RimuruTempest9** [fak1ch/FruitNinja#19]
https://github.com/fak1ch/FruitNinja/blob/dd639404d1a2bf7f5d84eadc120825f272f72e82/Assets/Scripts/GameInitializer.cs#L5-L12

Maybe make some fields with the `[SerializeField]` attribute that allow you to change the game initialization values from the inspector? Or even better, take these values from some `*.json` file?

**Comment by fak1ch** [comment]
Removed magical numbers from GameInitializer!
